version: "3.4"

services:

  backend:
    build: .
    container_name: backend_lnb_stock
    restart: always
    ports:
      - "8380:80"



networks:
  default:
    external : true
    name: lnb-network
